-- The ocean, said in the words the game already reads.
--
-- The ocean and its waypoints are authored here and read by a game, and the two
-- ends have to agree on fourteen names. Where they disagree the consumer's
-- running shape is canonical and MAPVIS moves: a composition of `slots` read as
-- `places` is discarded by one Array.isArray check and falls back to whatever
-- the reader has hard-coded, silently, with no error anywhere.
--
-- Two of the fourteen disagreements need a column rather than a rename.
--
--   version  the game stamps a saved position with the world version it was
--            taken in and refuses to resume a run when the number has changed.
--            updated_at cannot do that job: it moves when an author drags one
--            island, which would throw away everybody's saved position on every
--            save. So this is an integer that only counts
--            up when the composition itself really changed, and dragging a
--            waypoint or renaming a title does not touch it.
--
--   home     where a run with no vessel record starts, and where a graduate is
--            handed back to. One slot name for the whole ocean, and the
--            alternative is a slug hard-coded in the game that reads it.
alter table world add column if not exists version integer not null default 1;
alter table world add column if not exists home    text    not null default '';
