// Push every local map's working files into whatever bucket .env points at.
//
//   node server/db/sync-storage.mjs           say what would happen
//   node server/db/sync-storage.mjs --write   actually upload
//
// This exists because local disk and the bucket drifted: the direction sets a
// sprite is made of were written to work/<slug>/library/<name>/<heading>-<n>.png
// and never uploaded, so 1,038 files of paid generation lived on one laptop and
// nowhere else. It is also how a bucket move is done. Uploading from disk rather
// than copying bucket to bucket means the source is the superset, and it costs
// no download transactions on the bucket being left behind.
//
// The key layout is the one blobKeyForWorkPath already reads back:
//   work/<slug>/library/gull/3.png  ->  maps/<id>/library/gull/3.png
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { store } from '../store/blobs.mjs'
import { q, many } from './pool.mjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const WORK = path.join(ROOT, 'work')
const WRITE = process.argv.includes('--write')

// .prev is undo scratch and assets/ is export output that a publish rewrites,
// so neither is the irreplaceable half.
const SKIP = new Set(['.prev', 'assets'])

function walk(dir, base = '') {
  const out = []
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(e.name)) continue
    const rel = base ? base + '/' + e.name : e.name
    const p = path.join(dir, e.name)
    if (e.isDirectory()) out.push(...walk(p, rel))
    else out.push(rel)
  }
  return out
}

const TYPES = { '.png': 'image/png', '.json': 'application/json' }

const maps = await many('select id, slug from maps order by slug')
const s = store()

/* THE OTHER DIRECTION, run once before leaving a bucket behind.
 *
 * Push assumes disk is the superset, and for a map made on this laptop it is.
 * A map made anywhere else has bytes that exist only in the bucket, and those
 * have to come down before the bucket goes away. Publishes are deliberately not
 * pulled: a published version is regenerated by exporting again, and there are
 * thousands of them, which is a lot of download transactions spent on files
 * that can simply be rebuilt. */
if (process.argv.includes('--pull')) {
  let got = 0
  for (const m of maps) {
    for (const o of await s.list(`maps/${m.id}/`)) {
      const key = String(o.key || o)
      const rel = key.slice(`maps/${m.id}/`.length)
      const f = path.join(WORK, m.slug, ...rel.split('/'))
      if (fs.existsSync(f)) continue
      if (!WRITE) { console.log(`would pull ${m.slug}/${rel}`); got++; continue }
      fs.mkdirSync(path.dirname(f), { recursive: true })
      fs.writeFileSync(f, await s.get(key))
      got++
    }
  }
  console.log(WRITE ? `pulled ${got}` : `${got} file(s) would be pulled`)
  process.exit(0)
}
console.log(`bucket: ${s.kind}${s.bucket ? ' ' + s.bucket : ''}`)
console.log(WRITE ? 'writing\n' : 'dry run, nothing will be uploaded (pass --write)\n')

let total = 0
let sent = 0
for (const m of maps) {
  const dir = path.join(WORK, m.slug)
  if (!fs.existsSync(dir)) {
    console.log(`${m.slug}: no local folder, skipped`)
    continue
  }
  const files = walk(dir)
  const have = new Set((await s.list(`maps/${m.id}/`)).map((o) => String(o.key || o)))
  const todo = files.filter((f) => !have.has(`maps/${m.id}/${f}`))
  total += todo.length
  console.log(`${m.slug}: ${files.length} local, ${have.size} in bucket, ${todo.length} to upload`)
  if (!WRITE) continue
  for (const rel of todo) {
    const buf = fs.readFileSync(path.join(dir, ...rel.split('/')))
    await s.put(`maps/${m.id}/${rel}`, buf, TYPES[path.extname(rel).toLowerCase()] || 'application/octet-stream')
    if (++sent % 100 === 0) console.log(`  ${sent}/${total}`)
  }
}

console.log(WRITE ? `\ndone, ${sent} uploaded` : `\n${total} file(s) would be uploaded`)
await q('select 1')
process.exit(0)
